# syntax=docker/dockerfile:1.4

FROM node:22.16.0 AS shared-build
WORKDIR /
COPY --from=root tsconfig.json tsconfig.json
WORKDIR /shared
COPY --from=shared dist dist
COPY --from=shared package*.json .
COPY --from=shared tsconfig.json tsconfig.json
RUN npm install

FROM node:22.16.0 AS build
WORKDIR /

COPY --from=root tsconfig.json tsconfig.json
COPY --from=shared-build /shared/ /shared/

WORKDIR /frontend
COPY . .
RUN npm install

CMD ["npm", "run", "dev"]