name: cashflow

services:
    database:
        container_name: database
        image: postgres:17.5
        environment:
            POSTGRES_DB: cashflow
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        ports:
            - "5432:5432"
        volumes:
            - ./docker/pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U admin -d cashflow"]
            interval: 3s
            timeout: 2s
            retries: 5

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "3002:80"
        depends_on:
            - database
        volumes:
            - ./docker/pgadmin_data:/var/lib/pgadmin
